<p>예외(Exception)란?</p>
<ul>
<li>예외는 프로그램 실행 중 예상하지 못한 상황이 발생하는 것을 의미합니다.
  → 커피 쏟기
  → 대표적인 산술 예외: <code>10 / 0</code> (0 으로 나누기) </li>
<li>의도적으로 예외를 발생시킬 때는 <code>throw</code> 키워드를 통해 발생시킵니다.
  -&gt; 강제로 예외발생</li>
<li>예외를 처리하지 않으면 프로그램이 중단될 수 있습니다.</li>
<li>그래서 <code>예외처리(try-catch)</code>를 통해 프로그램이 안정적으로 실행되게 할 수 있습니다.</li>
</ul>
<br />

<hr />
<br />


<p>1.<strong>의도하지 않은 예외</strong></p>
<ul>
<li>아래 코드에서 <code>10 / 0</code> 연산을 수행하면서 <code>ArithmeticException</code> (산술예외)가 발생합니다.</li>
<li>0 으로 나누는 연산은 허용되지 않음으로 프로그램이 비정상적으로 종료됩니다.</li>
<li>예외를 처리하지 않으면 이후 코드는 실행되지 않습니다.<pre><code class="language-java">public class Main {
  public static void main(String[] args) {
      System.out.println(&quot;프로그램 시작&quot;);
      int result = 10 / 0; // ❌ 예외 발생 (ArithmeticException)
      System.out.println(&quot;이 문장은 실행되지 않음&quot;);
  }
}

</code></pre>
</li>
</ul>
<p>Exception in thread &quot;main&quot; java.lang.ArithmeticException: / by zero
    at chapter3.exception.Main.main(Main.java:8)</p>
<p>Process finished with exit code 1</p>
<pre><code>
&gt; try-catch문으로 예외처리하지 않으면 중간에 에러가 떠서 프로그램이 멈춤, 비정상적으로 종료됨

&lt;br&gt;

2.**의도적인 예외  - `throw`**
- 특정 조건에서 의도적으로 예외를 발생시킬 수도 있습니다.
    - 비즈니스 규칙을 위반한 경우(미성년자접근)
- 아래 코드에서 `age &lt; 18`  조건을 만족하면 `IllegalArgumentException` 을 발생시킵니다.
- `throw` 를 활용하면 특정 상황에서 예외를 명확하게 정의하고 제어할 수 있습니다.
```java
public class Main {
    public static void main(String[] args) {
        int age = 10;
        if (age &lt; 18) {
                // ✅ 의도적으로 예외를 발생시키는 부분
            throw new IllegalArgumentException(&quot;미성년자는 접근할 수 없습니다!&quot;);
        }
        System.out.println(&quot;....&quot;);
    }
}</code></pre><br />

<hr />
<br />

<p><strong><em>예외 구조와 종류에 대해서 학습해 봅시다.</em></strong></p>
<ul>
<li><strong><em>RuntimeException - UncheckedException</em></strong><ul>
<li><code>RuntimeException</code> 을 상속받는 모든 예외를 <code>UncheckedException</code> 이라고 합니다.</li>
<li>예외처리를 컴파일러가 확인하지 않습니다.</li>
</ul>
</li>
<li><strong><em>Exception - CheckedException</em></strong><ul>
<li><code>Exception</code> 클래스를 직접 상속받는 모든 예외를 <code>CheckedException</code> 이라고합니다. <code>RuntimeException</code>과 <code>RuntimeException</code> 을 상속받은 예외는 제외합니다.</li>
<li>예외처리를 컴파일러가 확인해 줍니다.</li>
</ul>
</li>
</ul>
<img src="https://velog.velcdn.com/images/mo00ai/post/6045dee4-575b-4a85-af23-665f62c5491d/image.png" style="width: 60%;" />

<br />

<p>예외 전파</p>
<ul>
<li>예외 전파는 메서드에서 발생한 예외가 해당 메서드 내에서 처리되지 않았을 때 메서드를 호출한 상위 메서드로 전달되는 과정을 말합니다.</li>
<li>예외가 프로그램 시작 지점(<code>main()</code>) 까지 전파되고 끝내 처리되지 않으면 프로그램이 비정상 종료 됩니다.</li>
<li>예외 전파를 <code>RuntimeException</code> 그리고 <code>Exception</code> 예시를 통해 알아봅시다.</li>
</ul>
<br />

<hr />
<br />



<p>1.언체크 예외 호출</p>
<ul>
<li><strong>컴파일러가 예외 처리를 강제하지 않는 예외입니다.</strong></li>
<li>예외 처리를 하지 않아도 컴파일 오류(빨간 줄) 가 발생하지 않습니다.</li>
<li>처리되지 않은 예외는 계속 프로그램 시작 지점까지 전파됩니다.</li>
<li>끝내 예외가 처리되지 않으면 프로그램이 비정상적으로 종료됩니다.</li>
<li><code>RuntimeException</code> 을 상속받는 모든 예외를 <code>UncheckedException</code> 이라고 합니다.</li>
</ul>
<p>try-catch문을 사용해서 예외처리함</p>
<ul>
<li><p>프로그램이 예외로 인해 비정상적으로 에러를 내면서 종료하지 않도록 try-catch문을 사용</p>
<pre><code class="language-java">public class Main {
  public static void main(String[] args) {
      ExceptionPractice exceptionPractice = new ExceptionPractice();

      // ✅ 상위로 전파된 예외처리
      try {
          exceptionPractice.callUncheckedException();

      } catch (RuntimeException e) { // ✅ 예외처리
          System.out.println(&quot;언체크 예외 처리&quot;);   
      } catch (Exception e) {
          System.out.println(&quot;체크 예외 처리&quot;);
      }

      System.out.println(&quot;프로그램 종료&quot;);
  }
}

</code></pre>
</li>
</ul>
<p>public class ExceptionPractice {
    public void callUncheckedException() {
        if (true) {
            System.out.println(&quot;언체크 예외 발생&quot;);
            throw new RuntimeException(); // ✅ 예외발생 
        }
    }
}</p>
<pre><code>
try 블럭
- 예외가 발생할 것 같은 로직을 넣기

catch 블럭
- 처리하고 싶은 에러를 매개변수로 넣음
- 블럭 내엔 처리 내용을 넣기

실행 순서
1. try 블럭 내 로직을 수행하다가 예외가 발생함
2. 예외 발생시 바로 상위 메서드를 찾아가는게 아니라 catch블럭을 찾아감
3. 발생한 예외를 처리할 수 있는지 확인
- throw new RuntimeException = RuntimeException e
- 동일하므로 처리할 수 있음 -&gt; 예외처리 함
- 저건 catch가 2개니까 예외 종류에 따라 다른 예외처리를 할 수 있도록 구조를 만듦
-&gt; 프로그램이 에러 뜨고 종료되지 않고 정상적으로 예외처리해서 에러날 것 같은 로직 다음 코드들도 수행가능함

&lt;br&gt;
&lt;br&gt;
&lt;br&gt;

2. 체크 예외 호출
- `Exception` 클래스를 직접 상속받는 모든 예외를 `CheckedException` 이라고 합니다.
    - `RuntimeException` 을 상속받는 예외는 제외.
- **컴파일러가 예외 처리를 강제하는 예외입니다.**
- 예외 처리를 하지 않으면 “컴파일 오류가 발생한다(코드에 빨간줄)” 라고 이해하시면 쉽습니다.
- 반드시 `try-catch`로 예외를 처리하거나 `throws` 키워드를 사용해야 합니다.
→ `throws` 로 예외 처리의 책임을 호출자에게 전가할 수 있습니다.

&lt;br&gt;
1. try-catch 활용해서 예외처리하기

```java
public void callCheckedException() {
            // ✅ try-catch 로 예외 처리
        try { 
            if (true) {
                System.out.println(&quot;체크예외 발생&quot;);
                throw new Exception();
            }
        } catch (Exception e) {
            System.out.println(&quot;예외 처리&quot;);
}


public class Main {
    public static void main(String[] args) {

        // 예외 실습 객체 인스턴스화
        ExceptionPractice exceptionPractice = new ExceptionPractice();

        // ✅ 체크예외 호출
        exceptionPractice.callCheckedException();
    }
}</code></pre><br />

<ol start="2">
<li>throws 활용해서 예외처리하기</li>
</ol>
<ul>
<li><p>throws 키워드를 사용하여 예외를 호출한 곳에서 처리하도록 강제하는 방식입니다.
→ (책임 전가)</p>
<pre><code class="language-java">public class ExceptionPractice {

  public void callCheckedException() throws Exception { // ✅ throws 예외를 상위로 전파
      if (true) {
          System.out.println(&quot;체크예외 발생&quot;);
          throw new Exception();
      }
  }

</code></pre>
</li>
</ul>
<p> public class Main {
    public static void main(String[] args) {</p>
<pre><code>    // 예외 실습 객체 인스턴스화
    ExceptionPractice exceptionPractice = new ExceptionPractice();

    // 체크 예외 사용
    // ✅ 반드시 상위 메서드에서 try-catch 를 활용해 주어야합니다.
    try {
        exceptionPractice.callCheckedException();
    } catch (Exception e) {
        System.out.println(&quot;예외처리&quot;);
    }
}</code></pre><p>}</p>
<pre><code>
&lt;br&gt;
&lt;br&gt;
&lt;br&gt;

***배운 내용을 정리해 봅시다.***
- 예외가 발생하고 처리되지 않으면 프로그램이 비정상적으로 종료될 수 있기 때문에 꼭 예외 처리는 필수입니다.
- `CheckedException` 은 컴파일러를 통해 개발자에게 반드시 처리해야 하는 예외를 알려줄 수 있습니다.
- `UncheckedException` 은 개발자가 충분히 예측하고 방지할 수 있는 경우 사용합니다.
    → 숫자를 0으로 나누는 오류 등은 코드 검토로 충분히 예방 가능합니다. 
    → 이런 예외 처리까지 `CheckedException` 으로 처리하도록 강제한다면 모든 예외 상황을 처리해야 하는 답답한 상황이 벌어져 개발 생산성이 저하되고 불필요한 코드가 많아질 수 있습니다.


&lt;br&gt;
&lt;br&gt;
&lt;br&gt;

---

&lt;br&gt;

예외처리 실습예제

```java
package chapter3.exception;

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        Exception exception = new Exception();

        while(true) {
            try {

                System.out.print(&quot;아이디를 입력하세요: &quot;);
                String id = scanner.next();
                System.out.print(&quot;아이디를 입력하세요: &quot;);
                int pw = scanner.nextInt();
                scanner.nextLine();

                //예외발생 가능성
                exception.exceptId(id, pw);

                System.out.println(&quot;로그인 성공&quot;);
                break;

            } catch (java.lang.Exception e) {
                System.out.println(e.getMessage());
            }
        }



    }
}</code></pre><pre><code class="language-java">public class Exception {
    public void exceptId(String id, int pw) throws java.lang.Exception {
        if(!id.equals(&quot;admin&quot;) || ! (pw == 1234)) {
            throw new java.lang.Exception(&quot;로그인 실패! 아이디 또는 비밀번호가 잘못되었습니다.&quot;);
        }
    }
}</code></pre>
<p>해석</p>
<blockquote>
<ol>
<li>main-&gt; 구현, Exception -&gt; 예외처리</li>
<li>객체는 while문 바깥에 둬서 한 번만 생성하게 함. 메모리 낭비 방지</li>
<li>while문 안에 try-catch문, 그리고 구현부를 둬서 올바른 아이디, 비번을 입력할 때까지 반복하게 함</li>
</ol>
</blockquote>
<br />

<p>try-catch</p>
<blockquote>
<ol>
<li>try 블록에서 오류가 발생할 수도 있는 구현부를 작성함 exception.exceptid(id,pw)에 틀린 아이디 비번 입력할 경우 예외 날리게 하는 코드를 작성</li>
<li>catch (java.lang.Exception e): try 블록에서 발생한 Exception을 잡아 e라는 변수에 저장.</li>
<li>e.getMessage(): 예외 객체(e)에 저장된 오류 메시지를 반환.</li>
<li>System.out.println(e.getMessage());: 예외 메시지를 콘솔에 출력.</li>
</ol>
</blockquote>
<br />
<br />

<p>exceptId 해석</p>
<br />

<ol>
<li>메서드 선언(exceptId)의 <code>throws</code><pre><code class="language-java">public void exceptId(String id, int pw) throws java.lang.Exception {</code></pre>
</li>
</ol>
<ul>
<li>이 메서드는 예외가 발생할 수 있으니, 호출한 쪽에서 처리(try-catch)하거나 다시 throws하라&quot;고 알려주는 역할</li>
<li>예외가 발생할 가능성이 있다고 경고하며 알림 (책임 전가)</li>
<li>실제로 예외를 던지지 않음, 예외처리를 상위 메서드에 미룸</li>
</ul>
<ol start="2">
<li>메서드 내부의 <code>throw</code><pre><code class="language-java">throw new java.lang.Exception(&quot;로그인 실패! 아이디 또는 비밀번호가 잘못되었습니다.&quot;);</code></pre>
</li>
</ol>
<ul>
<li>메서드 안쪽 코드에 있습니다.</li>
<li>실제로 예외 객체를 생성하고 발생(던지는) 역할을 합니다.</li>
<li>예외를 만들어 직접적으로 던지는 것이죠.</li>
</ul>
<p>예시)</p>
<pre><code class="language-java">throw new Exception(&quot;로그인 실패!&quot;);</code></pre>
<p>위와 같이 메시지를 넣으면</p>
<ul>
<li>예외가 발생한 이유를 getMessage()를 통해 전달할 수 있어요.</li>
<li>나중에 예외가 발생했을 때 왜 문제가 생겼는지 명확히 파악 가능합니다.</li>
</ul>
<pre><code class="language-java">catch(Exception e) {
    System.out.println(e.getMessage()); // &quot;로그인 실패!&quot; 출력
}</code></pre>
<p>저 메시지가 getMessage()에 담겨 예외 발생 원인 설명 용도로 쓰이게 됨
e.getMessage()는 <strong><em>예외(Exception) 객체에 저장된 오류 메시지를 문자열로 반환하는 메서드.</em></strong></p>
<br />

<blockquote>
<p>결론적으로:
throw는 직접 예외를 발생시키는 실제 행동
throws는 예외가 생길 가능성을 호출자에게 알려주는 경고</p>
</blockquote>
<br />

<p>Exception 클래스의 생성자 구조</p>
<pre><code class="language-java">// 기본 생성자 (메시지 없음)
public Exception();

// 문자열 메시지를 포함하는 생성자
public Exception(String message);

// 원인이 되는 예외를 전달하는 생성자
public Exception(Throwable cause);

// 메시지와 원인이 되는 예외 둘 다 전달하는 생성자
public Exception(String message, Throwable cause);</code></pre>
<pre><code>new Exception(&quot;로그인 실패! 아이디 또는 비밀번호가 잘못되었습니다.&quot;);</code></pre><p>-&gt; 2번째 생성자를 활용한 예시</p>
<br />
<br />


<hr />
<br />

<p>throws와 try-catch가 예외 처리에서 작동하는 순서</p>
<br />

<ol>
<li>throws 선언이 있는 메서드 정의<pre><code class="language-java">// 예외 발생 가능성을 선언함
public void exceptId(String id, int pw) throws Exception {
 if (!id.equals(&quot;admin&quot;) || pw != 1234) {
     throw new Exception(&quot;로그인 실패!&quot;);
 }
}</code></pre>
먼저 예외가 발생할 가능성이 있는 메서드를 정의할 때, throws를 붙입니다.
이 메서드는 자신을 호출하는 쪽으로 예외 처리를 넘기겠다고 선언한 것입니다.</li>
</ol>
<br />

<ol start="2">
<li>메서드를 호출하는 쪽에서 처리 (try-catch)<pre><code class="language-java">public static void main(String[] args) {
 try {
     exceptId(&quot;user&quot;, 1111); // 예외가 여기서 발생할 수 있음
 } catch(Exception e) {
     // exceptId 메서드에서 던진 예외를 여기서 잡아서 처리함
     System.out.println(&quot;에러 메시지: &quot; + e.getMessage());
 }
}</code></pre>
이 메서드를 호출할 때, 호출하는 쪽에서 반드시 예외 처리를 해야 합니다.
즉, try-catch를 쓰거나, 다시 상위 메서드로 예외 처리를 넘겨야 합니다.</li>
</ol>
<br />

<p>실행 흐름을 그림으로 보면:</p>
<pre><code>(호출자) main 메서드 ──→ exceptId(&quot;user&quot;, 1111) 호출
                        │
                        ▼
    exceptId 메서드 실행 (예외 조건 만족)
        │
        ▼
    throw new Exception(&quot;로그인 실패!&quot;) 실행
        │
        ▼ 예외 발생 ────▶ exceptId 즉시 종료
                        │
                        ▼
(예외 전달) ────▶ main 메서드의 catch 블록으로 이동
                        │
                        ▼
    catch(Exception e) { ... } 실행됨</code></pre><blockquote>
<p>throws는 메서드 선언에서 예외가 있을 수 있다고 경고할 뿐, 직접 예외를 던지지 않아요.
실제 예외는 메서드 내부의 throw에서 발생합니다.
발생한 예외는 호출자에게 전달되어 (try-catch 블록을 만나면) 처리됩니다.</p>
</blockquote>
<blockquote>
<p>실질적으로 catch블록을 발생시키는 건 exceptId의 throw!!!! throws는 걍 main에서 try-catch를 하도록 만든 거임
throw로 예외를 발생시키고, 그 예외를 catch 블록의 매개변수에 저장한 다음 e.getMessage로 오류메시지를 출력함.</p>
</blockquote>
<br />
<br />

<hr />
<br />

<p>그럼 RuntimeException이랑 Exception 중에 뭘 더 상용할까?</p>
<blockquote>
<p>내 예상 
-&gt; 컴파일러가 일일히 확인해주는 Exception이 낫지 않나?
---&gt; <strong><em>전혀 아님</em></strong>, <strong><em>Exception을 남발하면 불필요한 try-catch문을 남발하게 돼서 RuntimeException을 더 상용함</em></strong></p>
</blockquote>
<p> ✅ Exception vs RuntimeException 정리</p>
<table>
<thead>
<tr>
<th>구분</th>
<th>Exception (Checked)</th>
<th>RuntimeException (Unchecked)</th>
</tr>
</thead>
<tbody><tr>
<td><strong>처리 강제 여부</strong></td>
<td>✅ 컴파일러가 예외처리를 강제함</td>
<td>❌ 컴파일러가 강제하지 않음 (처리 선택 가능)</td>
</tr>
<tr>
<td><strong>언제 사용?</strong></td>
<td>파일 입출력, 네트워크, DB 연결 등 시스템 예외</td>
<td>사용자 입력 오류, 로직 오류 등 비즈니스 예외</td>
</tr>
<tr>
<td><strong>예외 처리 방법</strong></td>
<td>반드시 <code>try-catch</code> 또는 <code>throws</code>로 처리</td>
<td>필요할 때만 선택적으로 처리</td>
</tr>
<tr>
<td><strong>코드 간결성</strong></td>
<td>복잡하고 길어질 수 있음</td>
<td>코드가 간결하고 깔끔해짐</td>
</tr>
<tr>
<td><strong>사용 빈도</strong></td>
<td>상대적으로 적음</td>
<td>더 자주 사용됨 (추천)</td>
</tr>
<tr>
<td><strong>자주 사용하는 예시</strong></td>
<td>IOException, SQLException 등</td>
<td><code>IllegalArgumentException</code>, <code>IllegalStateException</code></td>
</tr>
</tbody></table>
<p>🚩 실제 많이 쓰이는 예시</p>
<ul>
<li>로그인 실패 → IllegalArgumentException (RuntimeException)</li>
<li>잘못된 파라미터 값 → IllegalArgumentException</li>
<li>상태가 적절하지 않을 때 → IllegalStateException</li>
<li>파일 읽기 실패, 네트워크 문제 등은 Checked Exception (IOException, SQLException 등)</li>
</ul>
<pre><code class="language-java">throw new IllegalArgumentException(&quot;잘못된 입력입니다.&quot;);
throw new IllegalStateException(&quot;상태가 올바르지 않습니다.&quot;);
throw new NullPointerException(&quot;필수 값이 비어있습니다.&quot;);</code></pre>